# Copyright (c) 2026 Pengshen Zhang
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================
# Qwen3-Omni ASR vLLM Online Service
# (OpenAI Compatible Format)
# Uses AsyncLLMEngine + FastAPI
# Provides standard OpenAI API interface
# ==============================================
import argparse
import asyncio
import json
import os
import time
from contextlib import asynccontextmanager
from typing import Any, AsyncGenerator, Dict, List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

# Environment variable configuration
os.environ['VLLM_USE_V1'] = '0'
os.environ['VLLM_WORKER_MULTIPROC_METHOD'] = 'spawn'

from vllm.engine.arg_utils import AsyncEngineArgs  # noqa: E402
from vllm.engine.async_llm_engine import AsyncLLMEngine  # noqa: E402
from vllm.sampling_params import SamplingParams  # noqa: E402
from vllm.utils import random_uuid  # noqa: E402

# ==============================================
# Global Variables
# ==============================================
engine: Optional[AsyncLLMEngine] = None
model_name: str = ""


# ==============================================
# OpenAI Compatible Request/Response Models
# ==============================================
class ChatMessage(BaseModel):
    """Chat message"""
    role: str
    content: str  # Prompt already processed by client


class ChatCompletionRequest(BaseModel):
    """Chat completion request (simplified format)"""
    model: str = ""
    # Prompt already processed via apply_chat_template by client
    prompt: str
    # Multimodal data (already processed by client)
    multi_modal_data: Optional[Dict[str, Any]] = None
    mm_processor_kwargs: Optional[Dict[str, Any]] = None
    # Sampling parameters
    temperature: float = 0.01
    top_p: float = 0.1
    top_k: int = 1
    max_tokens: int = 512
    stream: bool = False
    # vLLM specific parameters
    stop_token_ids: Optional[List[int]] = None
    # Session ID (for tracking multiple chunks of same audio,
    # UUID generated by client)
    session_id: Optional[str] = None


class ChatCompletionChoice(BaseModel):
    """Response choice"""
    index: int
    message: ChatMessage
    finish_reason: Optional[str] = None


class ChatCompletionResponse(BaseModel):
    """Chat completion response (OpenAI format)"""
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: Optional[Dict[str, int]] = None


class HealthResponse(BaseModel):
    """Health check response"""
    status: str
    model: str


# ==============================================
# FastAPI Application
# ==============================================


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifecycle management"""
    yield


app = FastAPI(
    title="Qwen3-Omni vLLM Service",
    description="OpenAI compatible Qwen3-Omni ASR service",
    version="1.0.0",
    lifespan=lifespan
)


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(
    request: Request, exc: RequestValidationError
):
    """Handle request validation errors, return detailed info"""
    errors = exc.errors()
    error_details = []
    for error in errors:
        error_details.append({
            "field": " -> ".join(str(loc) for loc in error["loc"]),
            "message": error["msg"],
            "type": error["type"]
        })

    print(f"[Validation Error] Path: {request.url.path}")
    print(f"  Error details: "
          f"{json.dumps(error_details, ensure_ascii=False, indent=2)}")

    return JSONResponse(
        status_code=422,
        content={
            "detail": error_details,
            "message": "Request validation failed, check parameters"
        }
    )


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check"""
    if engine is None:
        raise HTTPException(
            status_code=503, detail="Engine not initialized")
    return HealthResponse(status="healthy", model=model_name)


@app.get("/v1/models")
async def list_models():
    """List available models (OpenAI compatible)"""
    if engine is None:
        raise HTTPException(
            status_code=503, detail="Engine not initialized")

    return {
        "object": "list",
        "data": [{
            "id": model_name,
            "object": "model",
            "created": int(time.time()),
            "owned_by": "qwen"
        }]
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """Chat completion endpoint

    Client responsibilities:
    - Audio reading and preprocessing
    - apply_chat_template (generate complete prompt)
    - process_mm_info (process multimodal data)

    Server responsibilities:
    - Receive prompt and multi_modal_data
    - Execute vLLM inference
    - Return results
    """
    if engine is None:
        raise HTTPException(
            status_code=503, detail="Service not ready")

    if not request.prompt:
        raise HTTPException(status_code=400, detail="Empty prompt")

    # vLLM requires unique request_id (per inference request)
    request_id = random_uuid()
    # Session ID (for tracking multiple chunks of same audio)
    session_id = request.session_id

    try:
        # Build vLLM inputs
        inputs = {
            'prompt': request.prompt,
            'multi_modal_data': request.multi_modal_data or {},
            'mm_processor_kwargs': request.mm_processor_kwargs or {}
        }

        # Sampling parameters
        sampling_params = SamplingParams(
            temperature=request.temperature,
            top_p=request.top_p,
            top_k=request.top_k,
            max_tokens=request.max_tokens,
            stop_token_ids=request.stop_token_ids
        )

        # Execute inference
        if request.stream:
            # Streaming response
            return StreamingResponse(
                stream_chat_completions(
                    inputs, sampling_params, request_id,
                    request.model, session_id),
                media_type="text/event-stream"
            )
        else:
            # Non-streaming response
            final_output = None
            async for output in engine.generate(
                    inputs, sampling_params, request_id):
                final_output = output

            if final_output is None:
                raise HTTPException(
                    status_code=500, detail="No output generated")

            response_text = final_output.outputs[0].text
            print(f"[Response] session_id: {session_id}, "
                  f"request_id: {request_id} -> "
                  f"response: ##{response_text}##")

            return ChatCompletionResponse(
                id=request_id,
                created=int(time.time()),
                model=request.model or model_name,
                choices=[
                    ChatCompletionChoice(
                        index=0,
                        message=ChatMessage(
                            role="assistant", content=response_text),
                        finish_reason="stop"
                    )
                ]
            )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


async def stream_chat_completions(
    inputs: dict,
    sampling_params: SamplingParams,
    request_id: str,
    model: str,
    session_id: Optional[str] = None
) -> AsyncGenerator[str, None]:
    """Stream response generation (OpenAI SSE format)"""
    try:
        async for output in engine.generate(
                inputs, sampling_params, request_id):
            chunk = {
                "id": request_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": model or model_name,
                "choices": [{
                    "index": 0,
                    "delta": {
                        "content": output.outputs[0].text
                    },
                    "finish_reason": None
                }]
            }
            yield (f"data: {json.dumps(chunk, ensure_ascii=False)}\n\n")

        # Send end marker
        final_chunk = {
            "id": request_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": model or model_name,
            "choices": [{
                "index": 0,
                "delta": {},
                "finish_reason": "stop"
            }]
        }
        yield (f"data: {json.dumps(final_chunk, ensure_ascii=False)}\n\n")
        yield "data: [DONE]\n\n"

    except asyncio.CancelledError:
        yield f"data: {json.dumps({'error': 'cancelled'})}\n\n"
    except Exception as e:
        yield f"data: {json.dumps({'error': str(e)})}\n\n"


# ==============================================
# Engine Initialization
# ==============================================
async def init_engine(
    model: str,
    tensor_parallel_size: int = 1,
    gpu_memory_utilization: float = 0.9,
    max_model_len: int = 32768,
    max_num_seqs: int = 8
):
    """Initialize AsyncLLMEngine"""
    global engine, model_name

    model_name = model

    print("[Init]")
    print(f"  Model path: {model}")
    print(f"  Tensor parallel: {tensor_parallel_size}")
    print(f"  GPU memory utilization: {gpu_memory_utilization}")

    # Build engine arguments
    engine_args = AsyncEngineArgs(
        model=model,
        trust_remote_code=True,
        gpu_memory_utilization=gpu_memory_utilization,
        tensor_parallel_size=tensor_parallel_size,
        max_model_len=max_model_len,
        max_num_seqs=max_num_seqs,
        limit_mm_per_prompt={'image': 1, 'video': 1, 'audio': 1},
        seed=1234
    )

    # Create engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)

    print("  Engine initialization complete!")


# ==============================================
# Start Server
# ==============================================
async def run_server(
    model: str,
    host: str = "0.0.0.0",
    port: int = 8000,
    tensor_parallel_size: int = 1,
    gpu_memory_utilization: float = 0.9
):
    """Start server"""
    # Initialize engine
    await init_engine(
        model=model,
        tensor_parallel_size=tensor_parallel_size,
        gpu_memory_utilization=gpu_memory_utilization
    )

    # Start server
    config = uvicorn.Config(
        app, host=host, port=port, log_level="info")
    server = uvicorn.Server(config)
    await server.serve()


# ==============================================
# Main Function
# ==============================================
def main():
    parser = argparse.ArgumentParser(
        description='Qwen3-Omni vLLM Server (OpenAI Compatible)')
    parser.add_argument(
        '--model', '-m', type=str, required=True,
        help='Model path')
    parser.add_argument(
        '--host', type=str, default='0.0.0.0',
        help='Server address (default: 0.0.0.0)')
    parser.add_argument(
        '--port', type=int, default=8000,
        help='Server port (default: 8000)')
    parser.add_argument(
        '--tensor-parallel-size', '-tp', type=int, default=1,
        help='Tensor parallel size (default: 1)')
    parser.add_argument(
        '--gpu-memory-utilization', type=float, default=0.9,
        help='GPU memory utilization (default: 0.9)')
    parser.add_argument(
        '--gpu-ids', type=str, default='0',
        help='GPU IDs to use, e.g., "0,1,2,3"')
    args = parser.parse_args()

    # Set GPU
    os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu_ids
    print("[Config]")
    print(f"  CUDA_VISIBLE_DEVICES: {args.gpu_ids}")

    # Start server
    asyncio.run(run_server(
        model=args.model,
        host=args.host,
        port=args.port,
        tensor_parallel_size=args.tensor_parallel_size,
        gpu_memory_utilization=args.gpu_memory_utilization
    ))


if __name__ == '__main__':
    main()
